/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1 "sigs.k8s.io/secrets-store-csi-driver/apis/v1"
)

// FakeSecretProviderCaches implements SecretProviderCacheInterface
type FakeSecretProviderCaches struct {
	Fake *FakeSecretsstoreV1
	ns   string
}

var secretprovidercachesResource = v1.SchemeGroupVersion.WithResource("secretprovidercaches")

var secretprovidercachesKind = v1.SchemeGroupVersion.WithKind("SecretProviderCache")

// Get takes name of the secretProviderCache, and returns the corresponding secretProviderCache object, and an error if there is any.
func (c *FakeSecretProviderCaches) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SecretProviderCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(secretprovidercachesResource, c.ns, name), &v1.SecretProviderCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SecretProviderCache), err
}

// List takes label and field selectors, and returns the list of SecretProviderCaches that match those selectors.
func (c *FakeSecretProviderCaches) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SecretProviderCacheList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(secretprovidercachesResource, secretprovidercachesKind, c.ns, opts), &v1.SecretProviderCacheList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SecretProviderCacheList{ListMeta: obj.(*v1.SecretProviderCacheList).ListMeta}
	for _, item := range obj.(*v1.SecretProviderCacheList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretProviderCaches.
func (c *FakeSecretProviderCaches) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(secretprovidercachesResource, c.ns, opts))

}

// Create takes the representation of a secretProviderCache and creates it.  Returns the server's representation of the secretProviderCache, and an error, if there is any.
func (c *FakeSecretProviderCaches) Create(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.CreateOptions) (result *v1.SecretProviderCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(secretprovidercachesResource, c.ns, secretProviderCache), &v1.SecretProviderCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SecretProviderCache), err
}

// Update takes the representation of a secretProviderCache and updates it. Returns the server's representation of the secretProviderCache, and an error, if there is any.
func (c *FakeSecretProviderCaches) Update(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.UpdateOptions) (result *v1.SecretProviderCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(secretprovidercachesResource, c.ns, secretProviderCache), &v1.SecretProviderCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SecretProviderCache), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecretProviderCaches) UpdateStatus(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.UpdateOptions) (*v1.SecretProviderCache, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(secretprovidercachesResource, "status", c.ns, secretProviderCache), &v1.SecretProviderCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SecretProviderCache), err
}

// Delete takes name of the secretProviderCache and deletes it. Returns an error if one occurs.
func (c *FakeSecretProviderCaches) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(secretprovidercachesResource, c.ns, name, opts), &v1.SecretProviderCache{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretProviderCaches) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(secretprovidercachesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SecretProviderCacheList{})
	return err
}

// Patch applies the patch and returns the patched secretProviderCache.
func (c *FakeSecretProviderCaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SecretProviderCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(secretprovidercachesResource, c.ns, name, pt, data, subresources...), &v1.SecretProviderCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SecretProviderCache), err
}
