/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "sigs.k8s.io/secrets-store-csi-driver/apis/v1"
	scheme "sigs.k8s.io/secrets-store-csi-driver/pkg/client/clientset/versioned/scheme"
)

// SecretProviderCachesGetter has a method to return a SecretProviderCacheInterface.
// A group's client should implement this interface.
type SecretProviderCachesGetter interface {
	SecretProviderCaches(namespace string) SecretProviderCacheInterface
}

// SecretProviderCacheInterface has methods to work with SecretProviderCache resources.
type SecretProviderCacheInterface interface {
	Create(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.CreateOptions) (*v1.SecretProviderCache, error)
	Update(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.UpdateOptions) (*v1.SecretProviderCache, error)
	UpdateStatus(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.UpdateOptions) (*v1.SecretProviderCache, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SecretProviderCache, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SecretProviderCacheList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SecretProviderCache, err error)
	SecretProviderCacheExpansion
}

// secretProviderCaches implements SecretProviderCacheInterface
type secretProviderCaches struct {
	client rest.Interface
	ns     string
}

// newSecretProviderCaches returns a SecretProviderCaches
func newSecretProviderCaches(c *SecretsstoreV1Client, namespace string) *secretProviderCaches {
	return &secretProviderCaches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretProviderCache, and returns the corresponding secretProviderCache object, and an error if there is any.
func (c *secretProviderCaches) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SecretProviderCache, err error) {
	result = &v1.SecretProviderCache{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretprovidercaches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretProviderCaches that match those selectors.
func (c *secretProviderCaches) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SecretProviderCacheList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SecretProviderCacheList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretprovidercaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretProviderCaches.
func (c *secretProviderCaches) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secretprovidercaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a secretProviderCache and creates it.  Returns the server's representation of the secretProviderCache, and an error, if there is any.
func (c *secretProviderCaches) Create(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.CreateOptions) (result *v1.SecretProviderCache, err error) {
	result = &v1.SecretProviderCache{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secretprovidercaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretProviderCache).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a secretProviderCache and updates it. Returns the server's representation of the secretProviderCache, and an error, if there is any.
func (c *secretProviderCaches) Update(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.UpdateOptions) (result *v1.SecretProviderCache, err error) {
	result = &v1.SecretProviderCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretprovidercaches").
		Name(secretProviderCache.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretProviderCache).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *secretProviderCaches) UpdateStatus(ctx context.Context, secretProviderCache *v1.SecretProviderCache, opts metav1.UpdateOptions) (result *v1.SecretProviderCache, err error) {
	result = &v1.SecretProviderCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretprovidercaches").
		Name(secretProviderCache.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretProviderCache).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the secretProviderCache and deletes it. Returns an error if one occurs.
func (c *secretProviderCaches) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretprovidercaches").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretProviderCaches) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretprovidercaches").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched secretProviderCache.
func (c *secretProviderCaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SecretProviderCache, err error) {
	result = &v1.SecretProviderCache{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secretprovidercaches").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
