/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apisv1 "sigs.k8s.io/secrets-store-csi-driver/apis/v1"
	versioned "sigs.k8s.io/secrets-store-csi-driver/pkg/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/secrets-store-csi-driver/pkg/client/informers/externalversions/internalinterfaces"
	v1 "sigs.k8s.io/secrets-store-csi-driver/pkg/client/listers/apis/v1"
)

// SecretProviderCacheInformer provides access to a shared informer and lister for
// SecretProviderCaches.
type SecretProviderCacheInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SecretProviderCacheLister
}

type secretProviderCacheInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSecretProviderCacheInformer constructs a new informer for SecretProviderCache type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSecretProviderCacheInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSecretProviderCacheInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSecretProviderCacheInformer constructs a new informer for SecretProviderCache type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSecretProviderCacheInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretsstoreV1().SecretProviderCaches(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretsstoreV1().SecretProviderCaches(namespace).Watch(context.TODO(), options)
			},
		},
		&apisv1.SecretProviderCache{},
		resyncPeriod,
		indexers,
	)
}

func (f *secretProviderCacheInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSecretProviderCacheInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *secretProviderCacheInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1.SecretProviderCache{}, f.defaultInformer)
}

func (f *secretProviderCacheInformer) Lister() v1.SecretProviderCacheLister {
	return v1.NewSecretProviderCacheLister(f.Informer().GetIndexer())
}
